name: test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18, 20]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install AWS cli
        run: |
          # delete preexisting one
          sudo rm -rf /usr/local/aws-cli
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip -q awscliv2.zip
          sudo ./aws/install
          mkdir -p ~/.aws
          cat >> ~/.aws/credentials << EOF
          [default]
          aws_access_key_id = NULL
          aws_secret_access_key = NULL
          region = ap-southeast-1
          EOF

      - name: Install dependencies
        run: yarn install

      - name: Run dynamodb locally
        run: |
          mkdir -p docker/dynamodb
          docker compose up -d

      - name: Run tests
        run: yarn test
