name: test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18, 20]

    container:
      image: node:${{ matrix.node-version }}

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install AWS cli
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          ./aws/install
          mkdir -p ~/.aws
          cat >> ~/.aws/credentials << EOF
          [default]
          aws_access_key_id = NULL
          aws_secret_access_key = NULL
          region = ap-southeast-1
          EOF

      - name: Install dependencies
        run: yarn install

      - name: Run dynamodb locally
        run: yarn dynamodb &

      - name: Run tests
        run: yarn test
